language: node_js

node_js:
  - "0.10"
env:
  global:
    - NODE_ENV=test
    - HOST=https://ci.copylot.io
    - DATABASE_URL=postgres://postgres:@localhost/copylot_test
    - DATABASE_TEST_URL=postgres://postgres:@localhost/copylot_test
    - REDIS_URL=redis://root@localhost:6379
    - RABBITMQ_BIGWIG_RX_URL=amqp://guest:guest@localhost
    - RABBITMQ_BIGWIG_TX_URL=amqp://guest:guest@localhost
    - MAILGUN=key-5f24661d0cd778ead4f82082400ff8b7
    - MAILGUN_DOMAIN=copylot.io
    - MIXPANEL=72bbf9f234ec60d5ac625d3e746e062a
    - SENTRY=https://d08970b16bf34bda95a0b5c77c611b64:647db8a47d974ee2b67f2b6f30de18de@app.getsentry.com/48027

notifications:
  email: false
  slack: 'copylot:SWgYRBrkvxmjso4HWhhQ42IT#development'

addons:
  postgresql: "9.3"

services:
  - redis-server
  - rabbitmq

before_script:
  - psql -c 'create database copylot_test;' -U postgres
