language: node_js
node_js:
  - "0.10"
addons:
  postgresql: "9.3"
script:
  - "sails-migrations migrate"
before_script:
  - psql -c 'create database copylot-test;' -U postgres
install:
  — "npm install"
